baseurl: https://rlatam.blog/
languageCode: es
title: RLatam Blog
disqusShortname: https-rlatam-blog
googleAnalytics: ''
paginate: 10
footnotereturnlinkcontents: ↩
theme: hugo-icarus-theme

ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

permalinks:
  post: /:year/:month/:day/:slug

params:
  author: Irwing S. Saldaña
  avatar: assets/images/avatar.png
  gravatar : ""
  bio: Ecoinformática - Biogeografía - Evolución
  copyright: Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice).
  custom_css: []
  custom_js: []
  date_format: '2006-01-02'
  disable_mathjax: no
  location: Peru
  logo: assets/images/logo.png
  mainSections: post

  menu:
    - before: yes
      label: Inicio
      link: /
    - before: no
      label: Categorías
      link: categories/

  profile:
    follow_button: https://github.com/irwingss

  site_description: ''

  widgets:
    recent_articles: yes
    categories: yes
    tag_cloud: no
    tags: yes

social:
  behance: ''
  bitbucket: ''
  codepen: ''
  deviantart: ''
  dribbble: ''
  facebook: 'https://web.facebook.com/irwingsmith/'
  facebook_admin: ''
  flickr: ''
  foursquare: ''
  github: irwingss
  gitlab: ''
  googleplus: ''
  instagram: ''
  jsfiddle: ''
  linkedin: irssald
  medium: ''
  pinterest: ''
  reddit: ''
  slideshare: ''
  stackoverflow: ''
  tumblr: ''
  twitter: irssald
  twitter_domain: ''
  vimeo: ''
  vine: ''
  wordpress: ''
  xing: ''
  youtube: channel/UCOTqfoQKMc61N_za-R6Ve7Q
